image: gradle:5.4-jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dprism.verbose=true -Dtestfx.setup.timeout=10000"
stages:
  - test
  - build

test:
  stage: test
  script:
    - apt-get update && apt-get install openjfx -y
    - ./gradlew test
    - mkdir
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/reports/*
    expire_in: 1 week
    when: always

build:
  stage: build
  script:
    - rm src/main/java/module-info.java
    - mv MainMain.txt src/main/java/application/MainMain.java
    - sed -i 's/application.Main/application.MainMain/g' build.gradle
    - ./gradlew clean
    - ./gradlew shadowJar
    - mv build/libs/*.jar ./release-$(git rev-parse --verify HEAD --short=20).jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - ./release-*.jar
    expire_in: 1 month
